version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      ConnectionStrings__Connection: "Server=host.docker.internal,1433;Database=Unow;User Id=sa;Password=Root809!"
    ports:
      - "5000:80"
    networks:
      - unownet_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - unownet_network

volumes:
  sqlserver_data:

networks:
  unownet_network:
    driver: bridge
